server:
  port: 8080

spring:
  application:
    name: ms-pedido

  # 1. Configuração do Banco de Dados (Postgres)
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_pedido_db
    username: postgres # Conforme Etapa 1
    password: postgres # Conforme Etapa 1
    driver-class-name: org.postgresql.Driver

  # 2. Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # 3. Configuração do Flyway (Controle de Versão do Banco)
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # 4. Configuração do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configuração da Documentação OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /v3/api-docs # Caminho do JSON
  swagger-ui:
    path: /swagger-ui.html # Caminho da interface